services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "blog_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - main
  app:
    build: .
    container_name: app
    volumes:
      - .:/app/
    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - mysql
    restart: always
networks:
  main:
volumes:
  mysqldata:
