services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always
networks:
  main:
volumes:
  postgres_data:
